language: java
sudo: false # faster builds

arch: 
  - amd64
  - arm64
jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo apt-get install openjdk-8-jdk;
     export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-arm64/;
     export PATH=$JAVA_HOME:$PATH;
     iptables -A INPUT -i docker0 -j ACCEPT;
   fi
  - rm -rf $HOME/.m2/repository/org/glassfish/javax.el/3.0.1-b08
  - travis_wait 30 ./mvnw --batch-mode --no-transfer-progress clean install -DskipTests=false -DskipIntegrationTests=true -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
